env:
  global:
    - secure: P9iKF3d3/dyj0+7cQUgbB8Yzi5H/WH3WOOlipDE+tJFjPV7D8MrAetA8QibSm//yFhZaQfo8W1TDhME63mP6Nz0IPyU/RPoFs8YZcNUa6ABNQF3uoNNK7t9l9DoekcP7lfqNx2f5F9PaMhmnDVf8KUAHCUnPGUfx41iSkqKxp9MUP4Io8eUESd/u86KLIAqmL7u5WE8HSZbq74m9JZwKzBNxzpoaQ+6kdapXH6gy/EcuUwXcYWB4a4YB5Ml17sY90Rnp4VHKt05AgDcXwgR9IlYVZ6dNV4cyO7+ta2sn18k5J7lPOZ7wKhAPgSHCbH9Vv8PLzLbtyLdXctDsHeTCvU9XrAcXRUYFwqLkCW+O7BrEYXEmDIdmntanvo4wCiGTbkFVZtIgIQ4iFkxgTQAeqEn0UzJol5bOKxiY0hWy5AQySh7DML0glX4oyqDGy82QQ0T/FdET1wJ8yH5tHafVNqU7MHkOeHpjyVzkwQua8HvVCU0sgei3tmr+eIAnnVTwZ9VzvteH0Zzcudq6Ay/hXnksYHZ5cR2LNw3s5mtw7Oyd+MbIPtLBUOONHeeIB53nn9woFC5OL3xa2jeMxjZUQ/rVRNtj3Czu1ZBxhidOZGd64X0ix5T+zVbaxCclpLYvpod6WarLTWYJIytI4xyJGNm7lRzDrXfh29orhRcHF4g=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/CoinBlockersLists-hosts_git_ZeroDot1
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
