env:
  global:
    - secure: vxU1j8b4H1Sg7XogtaIOz05Gk+f0H0s+xhrkMsQSnFrYkjKcy5cth8QsWK2FVc3ttru0UjO3tmqUDCMUkQLS4c5C7chqoPZqNHEuSQjIkD1ZiJUMCeZXsv9J0UsPWE3iQlAWRabfm2OdTNB5bAsQ3xp2b0FLqPdQitrOqWq6ByaO/V7zmO6wDVuI8A+WdAi5AEzk5mecl6k9N3/zDIrqKFb1hw96EQlb/2Wx2Rtr+cW0pJmff5F0tYvR+mwzkg9qGwlrIV0x62KDEkvB3hMTMg6RTfZMtS6vZxua9bsPhCJi6jXFziqpBSGBRPG+25YXJfJImlwQzc8jRxS24HLYBamPwn3cZmwiM97lZ3LO6St5gPu1933cjQRh5/lJ2kmQCJKAmpQy3v3Im+ubtL0j8AB0gLSW91wz3Q1ukqKnvvN7qGxNaCptkFzAXP45FVuZz0l5vCCWKD5TPKB6amH4aKfEcVnUq8Pkn6nGlL5PNusdpkYGBrC6Jhvs1GME2N+iO1TqOia6rwyRskTy/NyHs/pMuTDEp6AHUZD3dUbd0mVrBV80nn29YNPicZotzQ5so9QfGh52w5Wl9/LkNJDCdONDSP7DAPhz/59FCHxbV8SxRhW5XK1YikJZxMlJD1hOe7ZLxyPCL/UrzZsYOwL1rTrv6tLLbFF31G5wVL2PSN0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/CoinBlockersLists-hosts_git_ZeroDot1
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
